// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Namesilo
{
    [NamesiloResourceType("namesilo:index:DnsRecord")]
    public partial class DnsRecord : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The domain the record belongs to.
        /// </summary>
        [Output("domain")]
        public Output<string?> Domain { get; private set; } = null!;

        /// <summary>
        /// The hostname for the new record (there is no need to include the .DOMAIN)
        /// </summary>
        [Output("rrhost")]
        public Output<string?> Rrhost { get; private set; } = null!;

        /// <summary>
        /// The TTL for the new record (default is 7207 if not provided)
        /// </summary>
        [Output("rrttl")]
        public Output<int?> Rrttl { get; private set; } = null!;

        /// <summary>
        /// The type of resources record to add. Possible values are A, AAAA, CNAME, MX, TXT, SRV and CAA
        /// </summary>
        [Output("rrtype")]
        public Output<string?> Rrtype { get; private set; } = null!;

        /// <summary>
        /// The value for the resource record
        /// </summary>
        [Output("rrvalue")]
        public Output<string?> Rrvalue { get; private set; } = null!;


        /// <summary>
        /// Create a DnsRecord resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DnsRecord(string name, DnsRecordArgs? args = null, CustomResourceOptions? options = null)
            : base("namesilo:index:DnsRecord", name, args ?? new DnsRecordArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DnsRecord(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("namesilo:index:DnsRecord", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DnsRecord resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DnsRecord Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new DnsRecord(name, id, options);
        }
    }

    public sealed class DnsRecordArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The domain the record belongs to.
        /// </summary>
        [Input("domain")]
        public Input<string>? Domain { get; set; }

        /// <summary>
        /// The hostname for the new record (there is no need to include the .DOMAIN)
        /// </summary>
        [Input("rrhost")]
        public Input<string>? Rrhost { get; set; }

        /// <summary>
        /// The TTL for the new record (default is 7207 if not provided)
        /// </summary>
        [Input("rrttl")]
        public Input<int>? Rrttl { get; set; }

        /// <summary>
        /// The type of resources record to add. Possible values are A, AAAA, CNAME, MX, TXT, SRV and CAA
        /// </summary>
        [Input("rrtype")]
        public Input<string>? Rrtype { get; set; }

        /// <summary>
        /// The value for the resource record
        /// </summary>
        [Input("rrvalue")]
        public Input<string>? Rrvalue { get; set; }

        public DnsRecordArgs()
        {
        }
        public static new DnsRecordArgs Empty => new DnsRecordArgs();
    }
}
