// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Namesilo
{
    [NamesiloResourceType("namesilo:index:Nameservers")]
    public partial class Nameservers : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The domain the nameservers are associated with.
        /// </summary>
        [Output("domain")]
        public Output<string?> Domain { get; private set; } = null!;

        /// <summary>
        /// Nameserver 1
        /// </summary>
        [Output("ns1")]
        public Output<string?> Ns1 { get; private set; } = null!;

        /// <summary>
        /// Nameserver 2
        /// </summary>
        [Output("ns2")]
        public Output<string?> Ns2 { get; private set; } = null!;


        /// <summary>
        /// Create a Nameservers resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Nameservers(string name, NameserversArgs args, CustomResourceOptions? options = null)
            : base("namesilo:index:Nameservers", name, args ?? new NameserversArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Nameservers(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("namesilo:index:Nameservers", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Nameservers resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Nameservers Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Nameservers(name, id, options);
        }
    }

    public sealed class NameserversArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The domain the nameservers are associated with.
        /// </summary>
        [Input("domain", required: true)]
        public Input<string> Domain { get; set; } = null!;

        /// <summary>
        /// Nameserver 1
        /// </summary>
        [Input("ns1", required: true)]
        public Input<string> Ns1 { get; set; } = null!;

        /// <summary>
        /// Nameserver 2
        /// </summary>
        [Input("ns2", required: true)]
        public Input<string> Ns2 { get; set; } = null!;

        public NameserversArgs()
        {
        }
        public static new NameserversArgs Empty => new NameserversArgs();
    }
}
